### ISSUE TITLE
Return promise with sections from constructor

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/config#30]
Now we use:
```js
const config = await new Config(path);
const value = config.sections.<name>.<field>;
```
We can't just use `await new Config(path).sections` because await will be applied to sections, not to the value returned from constrictor. But if we will return promise with sections from constructor instead of promise with config instance, we can do following:
```js
const sections = await new Config(path);
const value = sections.<name>.<field>;
```

**Comment by tshemsedinov** [comment]
semver major, 2.0.0

**Comment by belochub** [comment]
@tshemsedinov Can't the caller just use destructuring if they only need the `sections` field from the config?
```js
const { sections } = await new Config(path);
```

Unrelated to that, I, personally, don't think returning a `Promise` value from a constructor provides a good developer experience, considering the class originally does not extend `Promise`, this makes it confusing to the caller and the readers of the code. Besides that, having the constructor implicitly start some asynchronous operation that must be awaited before the object becomes usable is also not very developer-friendly. A good alternative would be creating an async static method for that purpose, that will construct the object and load the data into it, returning the object itself or some property in it, for convenience.
